name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t spam-classifier .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: docker run --rm spam-classifier pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy application
        run: docker-compose up -d